### PR TITLE
static: add generic nvidia udev rules

### PR DESCRIPTION
**Pull request by xnox**
These integrate nvidia graphics cards with logind and enable power management.

### CODE REVIEW

**Comment by alfonsosanchezbeato** [comment]
Should this maybe come from a snapd interface with a udev slot instead? cc @pedronis 

Also, is this coming from a deb?

**Comment by xnox** [comment]
This will not come from a deb, because each one of them is versioned on per nvidia series, and they contain other commands/stanzas that cannot be executed on core. These are only relevant pieces that core needs.

I currently do not wish to develop a unique interface that will achieve this, as it is a system behavior, not something that individual snaps would want to request.

**Comment by pedronis** [comment]
we do ship udev rules with the bases, so I'm not against this as it also relate to logind which is not shipped in a separate snap, we can revisit this for core24 as we learn more on our journey to support graphics stacks

**Review by pedronis — APPROVED** [review]
I'm not opposed to this as such

**Review by alfonsosanchezbeato — APPROVED** [review]
Thanks for the comments, I think this makes sense

**Pull request merged**
