### PR TITLE
core: add pkcs11 dependencies

### PR DESCRIPTION
**Pull request by kubiko**
Add pkcs11 dependencies into core20 base snap

### CODE REVIEW

**Comment by xnox** [comment]
As far as i understand this will add pkcs#11 dependencies/libraries to the core22 snap; and it will also enable p11-kit-client provider in the default proxy pkcs#11 provider, which will try to connect to local socket which p11-kit-server should provide. I am assuming that sockets will be provided by something external/device specific.

module: opensc-pkcs11.so is available too, which one can opt into by configuring individual user account (via ~/.config), or system (via /etc) to use.

I'm not sure if it makes sense to have p11-kit-client module enabled by default in core, or if custom devices that provide p11-kit-server can also configure and activate p11-kit-client module.

Hopefully I understand all of the above correctly.

**Comment by valentindavid** [comment]
I am surprised by `/usr/lib/x86_64-linux-gnu/engines-3/pkcs11.la`. I do not think that openssl uses `lt_dlopen`, so it must be a useless file. Is that an oversight in `libengine-pkcs11-openssl` Ubuntu package?

Not sure about the use for `/etc/xdg/autostart/pkcs11-register.desktop`.

What is libopts for?

There are 2 dead symlinks in `/usr/lib/x86_64-linux-gnu/pkcs11/`.

Also there are 2 bash completion configuration that might not be useful: `goid-tool` and `pkcs11-register`

**Comment by valentindavid** [comment]
Did not we want `opensc-pkcs11.so` to be only used in snaps that manage the smart cards/dongles. It feels that it should not be in core. Maybe we should remove all `opensc-pkcs11` (it is a dependency of opensc)

**Comment by kubiko** [comment]
Rebase and push to remove dependency on ppa.

The agreement is to go ahead and use the pkcs11-tool from the archive as it is, to maintain current behaviour.
Most of the use cases are using openssl which uses libp11 which already defaults to the p11-proxy.

**Comment by kubiko** [comment]
@valentindavid fair point about `opensc-pkcs11.so` and it'd also reming anybody calling `pkcs11-tool` that default module is not there.

**Review by valentindavid — APPROVED** [review]
Same comments as core20 PR.

**Review by xnox — APPROVED** [review]

**Comment by xnox** [comment]
Note that i have no powers to merge, build, or release this change.

**Pull request merged**
