### PR TITLE
66-snapd-autoimport.rules: only import from removable disks

### PR DESCRIPTION
**Pull request by valentindavid**

### CODE REVIEW

**Review by alfonsosanchezbeato — COMMENTED** [review]
I think this is fine, but this needs some double check from field as maybe we have put user assertions in the past in normal partitions of a non-removable disk for some reason, so I've added @kubiko as a reviewer.

**Comment by valentindavid** [comment]
@alfonsosanchezbeato I suggest we do not backport that. But it would be nice to be in core24. My understanding is that we documented it only for "removable USB storage device".

**Review by Meulengracht — APPROVED** [review]
Thank you, lets await @kubiko 's approval

**Comment by alfonsosanchezbeato** [comment]
> @alfonsosanchezbeato I suggest we do not backport that. But it would be nice to be in core24. My understanding is that we documented it only for "removable USB storage device".

Yes, +1 on not backporting

**Review by kubiko — APPROVED** [review]
+1 from me, very neat. Thank you @valentindavid!
As for backport, I am not opposed to backport, as this was always advertised as something only functioning with external media, a prime use-case USB pen drive. I believe there was even an effort on UC20 or so to explicitly exclude internal drives.

**Review by alfonsosanchezbeato — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
